<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
// use CodeIgniter\I18n\Time;

class UserSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                // ============================================================== ADMIN
                'nama'          => 'Yoka Prasetia',
                'email'         => '221910846@stis.ac.id',
                'no_hp'         => '0895379261962',
                'domisili'      => 'Yogyakarta',
                'nim'           => '221910846',
                'kelas'         => '4SI2',
                'angkatan'      => '61',
                'tingkat'       => 'Tingkat IV',
                'tanggal_lahir' => '2002-01-20',
                'password'      => password_hash('221910846', PASSWORD_DEFAULT),
                'role'          => 'Admin',
                'alamat_kost'   => 'Jl. Solihun',
                'jenis_kelamin' => 'Laki-Laki',
                'status'        => 'Aktif',
            ],
            [
                // ============================================================== KETUA
                'nama'          => 'Ketua Rohis',
                'email'         => '333312213@stis.ac.id',
                'no_hp'         => '0895379261943',
                'domisili'      => 'Jakarta',
                'nim'           => '333312213',
                'kelas'         => '4SI1',
                'angkatan'      => '61',
                'tingkat'       => 'Tingkat IV',
                'tanggal_lahir' => '2002-04-20',
                'password'      => password_hash('333312213', PASSWORD_DEFAULT),
                'role'          => 'Ketua',
                'alamat_kost'   => 'Jl. Solihun',
                'jenis_kelamin' => 'Perempuan',
                'status'        => 'Aktif',
            ],
            // ============================================================== Humas
            [
                'nama'          => 'Humas Rohis',
                'email'         => '333310880@stis.ac.id',
                'no_hp'         => '0895123456786',
                'domisili'      => 'Tangerang',
                'nim'           => '333310880',
                'kelas'         => '2KS3',
                'angkatan'      => '63',
                'tingkat'       => 'Tingkat II',
                'tanggal_lahir' => '2003-08-24',
                'password'      => password_hash('333310880', PASSWORD_DEFAULT),
                'role'          => 'Humas',
                'alamat_kost'   => 'Jl. Sensus II',
                'jenis_kelamin' => 'Laki-Laki',
                'status'        => 'Aktif',
            ],
            // ============================================================== BENDAHARA
            [
                'nama'          => 'Bendahara Rohis',
                'email'         => '333310886@stis.ac.id',
                'no_hp'         => '0895123456785',
                'domisili'      => 'Bengkulu',
                'nim'           => '333310886',
                'kelas'         => '1ST4',
                'angkatan'      => '64',
                'tingkat'       => 'Tingkat I',
                'tanggal_lahir' => '2004-01-01',
                'password'      => password_hash('333310886', PASSWORD_DEFAULT),
                'role'          => 'Bendahara',
                'alamat_kost'   => 'Gg. Asem',
                'jenis_kelamin' => 'Perempuan',
                'status'        => 'Aktif',
            ],
            // ============================================================== ANGGOTA
            [
                'nama'          => 'Anggota Rohis Pertama',
                'email'         => '333310740@stis.ac.id',
                'no_hp'         => '0895123456784',
                'domisili'      => 'Aceh',
                'nim'           => '333310740',
                'kelas'         => '4SI2',
                'angkatan'      => '61',
                'tingkat'       => 'Tingkat IV',
                'tanggal_lahir' => '2000-06-01',
                'password'      => password_hash('333310740', PASSWORD_DEFAULT),
                'role'          => 'Anggota',
                'alamat_kost'   => 'Gg. Ayub',
                'jenis_kelamin' => 'Laki-Laki',
                'status'        => 'Aktif',
            ],
            [
                'nama'          => 'Anggota Rohis Kedua',
                'email'         => '333313422@stis.ac.id',
                'no_hp'         => '0895123456783',
                'domisili'      => 'Bangka',
                'nim'           => '333313422',
                'kelas'         => '4SK1',
                'angkatan'      => '61',
                'tingkat'       => 'Tingkat IV',
                'tanggal_lahir' => '2001-01-23',
                'password'      => password_hash('333313422', PASSWORD_DEFAULT),
                'role'          => 'Anggota',
                'alamat_kost'   => 'Gg. Ayub',
                'jenis_kelamin' => 'Laki-Laki',
                'status'        => 'Aktif',
            ],
            [
                'nama'          => 'Anggota Rohis Ketiga',
                'email'         => '333308898@stis.ac.id',
                'no_hp'         => '0895123456782',
                'domisili'      => 'Yogyakarta',
                'nim'           => '333308898',
                'kelas'         => '3D32',
                'angkatan'      => '62',
                'tingkat'       => 'Tingkat III',
                'tanggal_lahir' => '2002-01-03',
                'password'      => password_hash('333308898', PASSWORD_DEFAULT),
                'role'          => 'Anggota',
                'alamat_kost'   => 'Gg. Santai',
                'jenis_kelamin' => 'Perempuan',
                'status'        => 'Aktif',
            ],
            [
                'nama'          => 'Anggota Rohis Keempat',
                'email'         => '333310845@stis.ac.id',
                'no_hp'         => '0895123456781',
                'domisili'      => 'Yogyakarta',
                'nim'           => '333310845',
                'kelas'         => '4SK1',
                'angkatan'      => '62',
                'tingkat'       => 'Tingkat III',
                'tanggal_lahir' => '2002-03-14',
                'password'      => password_hash('333310845', PASSWORD_DEFAULT),
                'role'          => 'Anggota',
                'alamat_kost'   => 'Gg. Ggu',
                'jenis_kelamin' => 'Laki-Laki',
                'status'        => 'Aktif',
            ],
            [
                'nama'          => 'Anggota Rohis Kelima',
                'email'         => '333308451@stis.ac.id',
                'no_hp'         => '0895123456443',
                'domisili'      => 'Jawa Timur',
                'nim'           => '333308451',
                'kelas'         => '4SK1',
                'angkatan'      => '63',
                'tingkat'       => 'Tingkat II',
                'tanggal_lahir' => '2002-03-14',
                'password'      => password_hash('333308451', PASSWORD_DEFAULT),
                'role'          => 'Anggota',
                'alamat_kost'   => 'Gg. Sempit',
                'jenis_kelamin' => 'Perempuan',
                'status'        => 'Aktif',
            ],
        ];
        // Banyak data
        $this->db->table('users')->insertBatch($data);
    }
}
